### PR TITLE
Header translated for BlackLivesMatter

### PR DESCRIPTION
**Pull request by mesutissimo**
Change the header with proper translation.

image

### CODE REVIEW

**Comment by alioguzhan** [comment]
The message in the banner should be supported by every individual in the planet. Yet, this is heavily culture and geography related. Specifically, USA. In Turkey, that does not mean too much to people here. We don't have that racism problem against black people here. And by putting that message to the Turkish website, I don't want to act like we have it here, too.

But, here is a counter-argument:

The bottom-line is about a global value. And since we are a part of the globe, we should support and spread this message.


Let’s keep this PR open for now. I am open to suggestions and discussions.

**Comment by yunusemredilber** [comment]
Fair enough. What about only translating "Support the Equal Justice Initiative" part? Even we don't have too many racism problems against black people here, there might be some people who want to help our black-skinned friends in the US.

**Comment by alioguzhan** [comment]
> Fair enough. What about only translating "Support the Equal Justice Initiative" part? Even we don't have too many racism problems against black people here, there might be some people who want to help our black-skinned friends in the US.

That makes sense. What do you think @mesutissimo ?

**Comment by mesutissimo** [comment]
Yes @alioguzhan, suggestion of @yunusemredilber really makes sense. On the other hand, BLM slogan does not sounding well in Turkish. Let's keep it same and translate only the second part.

**Pull request merged**
